dataset:
    name: 'dataset'
    max_samples: 1

annotator:
    method : ''

predictor:
    method : 't2i'
    config:
        t2i:
            type: 'stability'
            name: 'core'
            "image_size": [1024,1024]
            "quality": "standard"
            "output_path": ''
        mode: 'prediction'

meta_prompts:
    folder: 'prompts/meta_prompts_image_generation'

eval:
    function_name: 't2i_vlm_score'
    llm:
        type: 'google'
        name: 'gemini-1.5-pro-latest'
    num_workers: 1
    source_image_folder: ''
    num_large_errors: 4
    error_threshold: 5
llm:
    type: 'google'
    name: 'gemini-1.5-pro-latest'
    temperature: 0.8
