openai:
  OPENAI_API_KEY: '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'
  OPENAI_ORGANIZATION: 'Personal'

azure:
  AZURE_OPENAI_API_KEY: ''
  AZURE_OPENAI_ENDPOINT: ''
  OPENAI_API_VERSION: ''

google:
  GOOGLE_API_KEY: ''
